### ISSUE TITLE
Enum not parsed

### ISSUE THREAD

**Issue by LudovicGuerra** [jnikula/hawkmoth#19] opened 2020-06-16 22:29 UTC
Thank you for your last help.
Sphinx 3.1 (can be the reason)
I have an other request, im trying to parse this file: 

```
/**
 * Real-time clock definition type
 */

/*
 * Copyright (c) 2010 
 * ATADADA
 * TADADA
 * TADADA
 */

#ifndef _DRV_RTC_H_
#define _DRV_RTC_H_

/*------------------------------- Include Files -----------------------------*/
#include "sys/status.h"

#include <stdint.h>
/*-------------------------------- Definitions ------------------------------*/

/*----------------------------------- Types ---------------------------------*/

/** The POSIX time used in the RTC */
typedef uint64_t rtc_time_t;

/**
 * The list of all command used with :c:func:`drv_rtc_ioctl` accepted on the RTC
 */
enum rtc_command
{
  /** Configure the RTC */
  RTC_CMD_CONFIGURE,
  /** Retrieve the time from RTC */
  RTC_CMD_GET_TIME,
  /** Set the time on the RTC */
  RTC_CMD_SET_TIME
};

/**
 * Here is describe the low level API as defined by the Hig level RTC driver
 */
typedef struct drv_rtc_func_s
{
  /** Initialize the hardwareC */
  sys_status_t (*init)( void );
  /** Set the hardware to a specific POSIX time */
  sys_status_t (*set_time)( rtc_time_t );
  /** Get the time in POSIX format */
  sys_status_t (*get_time)( rtc_time_t* );
  /** Configure the HW RTCX */
  sys_status_t (*configure)( uint64_t );
} drv_rtc_func_t;
```

And I receive this error:

> C:\Users\ludovic.guerra\Desktop\Code\f1\ula//include/drv/rtc.h:27: WARNING: Type must be either just a na
me or a typedef-like declaration.
If just a name:
  Error in declarator or parameters
  Invalid C declaration: Expected identifier in nested name, got keyword: enum [error at 4]
    enum rtc_command
    ----^
If typedef-like declaration:
  Error in declarator or parameters
  Invalid C declaration: Expected identifier in nested name. [error at 16]
    enum rtc_command
    ----------------^

> C:\Users\ludovic.guerra\Desktop\Code\f1\ula//include/drv/rtc.h:40: WARNING: Type must be either just a na
> me or a typedef-like declaration.
> If just a name:
>   Error in declarator or parameters
>   Invalid C declaration: Expected identifier in nested name, got keyword: struct [error at 6]
>     struct drv_rtc_func_s
>     ------^
> If typedef-like declaration:
>   Error in declarator or parameters
>   Invalid C declaration: Expected identifier in nested name. [error at 21]
>     struct drv_rtc_func_s
>     ---------------------^

**Comment by jnikula** [comment] 2020-12-15 20:02
Apologies for the looong delay in response. I presume these are indeed caused by sphinx 3. Should be fixed when we get pull #26 merged.

**Comment by LudovicGuerra** [comment] 2020-12-16 14:46
Glad to hear you are working back on it, let's say it's our regalo de Navidad.

**Comment by jnikula** [comment] 2020-12-26 11:33
Presumed fixed in master, please reopen if the problem persists. (No release yet with the fix though.)

**Closed by jnikula** 2020-12-26 11:33 UTC
