### ISSUE TITLE
Add support for pulling in docs for a single function/struct/enum

### ISSUE THREAD

**Issue by jekstrand** [jnikula/hawkmoth#51] opened 2021-06-16 15:06 UTC
I would really like to be able to write sphinx-style documentation where there is prose to tie everything together and then docs for structs, functions, etc. are pulled in where they make sense rather than wherever they happen to land in the file.  This seems especially important for C where you don't have strict class hierarchies grouping things together.  Unfortunately, hawkmoth can't do this, at least not today.

**Comment by jnikula** [comment] 2021-06-16 15:27
Thanks for the request. As said elsewhere, this is something I'd like to add. The little I've looked into it so far, there are some opens that I could use some early user feedback for. Otherwise I'll just do something that's easy for me. :)

1. For structs, unions and enums, is it enough granularity to be able to pull in the documentation for a struct/union and all its members together, and an enum and all its enumerator values together? They group nicely in C level, and I think would be more complicated to split up.
2. If you pick and choose documentation for specific C symbols, whose responsibility is it to pull in all the documentation from a file? The user? Or is the expectation to have an "all the rest" option or a warning for not pulling in everything?

**Comment by jnikula** [comment] 2021-06-16 15:40
For implementation details, some musing:

It's possible to extend the Sphinx Python autodoc extension for this. It does have a bunch of useful stuff. On the other hand, it's written for Python and some of that gets in the way. We've also repeatedly seen Sphinx just break backward compatibility for downstreams. The more intimately tied we are with Sphinx internals, the more likely we are to be caught by some incompatible upstream change.

Each C source file should only be parsed once (well, once per file + identical compiler flags), not each time there's a directive to parse something from that file. We need a way to store the parsed stuff across multiple directives, perhaps across multiple directives across multiple `.rst` documents.

@BrunoMSantos Any thoughts here? This is all related to https://gitlab.freedesktop.org/mesa/mesa/-/issues/4931 which could lead to a big time user for the project.

**Comment by jekstrand** [comment] 2021-06-16 15:45
For 1, I'm not sure what you're asking.  Are you looking for a comment at the top of the struct that has everything?  Or are you asking if I want to be able to pull in a single struct member?  I have no interest in pulling in a single member.  I just want to be able to say

    .. c:autostruct:: isl_struct
        :members:

And have it pull in everything.  A lot of doc solutions have a `:members:` thing you have to include if you want the full docs; otherwise you just get the over-all struct docs.  I don't know if you want to add that complexity but it might be good to require `:members:` even if you don't so we don't run into backwards compatibility issues if it ever is added.

For 2, not sure.  We don't have a lot of file-level docs in Mesa and I'm not sure I like them in general.  They're great if your files are well-organized but less great if stuff is scattered like it is in Mesa.  I do like what kerneldoc does where comments can start with "DOC: " and provide a mechanism to pull those in by name.
```
/**
 * DOC: document stuff
 *
 * Lorem Ipsum here are some docs
 */
```
and, in the RST,
```
.. kernel-doc:: path/to/my/file.c
    :doc: document stuff
```
If we wanted things to be more RSTy, we could allow something like this:
```
/**
 * Document Stuff
 * --------------
 *
 * Lorem Ipsum here are some docs
 */
```
and then, in the RST file,
```
.. c:autodoc: myfile.h
    :heading: Document Stuff
```

**Comment by BrunoMSantos** [comment] 2021-06-16 16:22
> @BrunoMSantos Any thoughts here? This is all related to https://gitlab.freedesktop.org/mesa/mesa/-/issues/4931 which could lead to a big time user for the project.

I do in fact! This all reminds me of [this](https://github.com/jnikula/hawkmoth/pull/9) dropped pull request and the discussion that ensued. **If I understand this issue correctly**, this would be exactly what I meant there. I'd even point out the example at the top of this comment [here](https://github.com/jnikula/hawkmoth/pull/9#issuecomment-485980352) as an illustration of what I think this is and what it would look like. Can you confirm @jekstrand ?

Already at the time @jnikula mentioned the issue of caching as well, which would be crucial here. I also didn't read the whole thread again, but there might be a few other important bits to consider in there. I'd say my views on it are substantially the same though and I wouldn't mind having this as it would in fact be more 'Sphinxy' than what we currently have.

**Comment by jnikula** [comment] 2021-06-16 16:28
I think the concepts are related but slightly different. I think what @jekstrand is asking is a more direct approach of writing prose and adding selected documentation from comments in the middle. That's much easier than grouping I think, and especially so if grouping means tying together documentation comments from several C files.

**Comment by jekstrand** [comment] 2021-06-16 16:28
I like this:
```
.. c:autofunction:: path/to/main.c another_function
```
It'd be nice if it didn't require the file to be specified but if it requires the file, I guess that's ok.  I guess what I'd ideally like is
```
.. c:autofunction:: my_func
```
which works as long as there's only one `my_func()` in the project.  If there's multiple, it gives a warning and you have to do
```
.. c:autofunction:: path/to/my/file.c my_func
```
That way, for a very well namespaced project like Mesa, we wouldn't have to have all those file paths in there.

**Comment by jnikula** [comment] 2021-06-16 16:34
This goes down to implementation details, but not requiring the filename changes when and how we parse files completely. Now it's all based on the `.. c:autodoc::` directive. Everything starts from the files specified there. If that wasn't the case, we'd have to parse all the C files first, and then figure out the references in the directives. Seems like quite a drastic change to me.

**Comment by jnikula** [comment] 2021-06-16 16:43
Earlier, for 1, the question I was after, if you have:

```
.. c:autostruct:: file.c foo_struct
```
possibly with a `:members:` specification, then is it enough that is the *only* place where you can pull in documentation for that struct and its members? i.e. you wouldn't be able to do:

```
.. c:autostruct:: file.c foo_struct
   :members: foo bar

.. c:autostruct:: file.c foo_struct
   :members: baz

.. c:autostruct:: file.c foo_struct
   :members:
```
IOW, the granularity is at the struct level.

**Comment by jekstrand** [comment] 2021-06-16 16:52
> EDIT: And there would _not_ be support for:
> 
> ```rst
> .. c:automember:: file.c foo_struct.bar
> ```

That's fine for now.  At the moment, I don't see any value in anything beyond
```rst
.. c:autostruct:: file.c foo_struct
   :members:
```

**Comment by jekstrand** [comment] 2021-06-16 16:55
> This goes down to implementation details, but not requiring the filename changes when and how we parse files completely. Now it's all based on the `.. c:autodoc::` directive. Everything starts from the files specified there. If that wasn't the case, we'd have to parse all the C files first, and then figure out the references in the directives. Seems like quite a drastic change to me.
> 
> EDIT: _Maybe_ it would be possible to specify a file, or a group of files, in a directive first, and then have the subsequent directives in the `.rst` document refer to symbols within those files.

If we have to list the filename for now, I think that's ok for now.  Being able to just throw around struct/function names would be nice but not strictly necessary.

**Comment by BrunoMSantos** [comment] 2021-06-16 17:33
What about top level comments? We currently allow this form of composition directly in the source:

```c
/**
 * Section 1
 * =========
 */

/** ...  */
void fun_1(void);

/**
 * Section 2
 * =========
 */

/** ... */
void fun_2(void);
```

I do like this feature, even if that's not how sphinx was intended to work perhaps. But how would we handle these in the future? So, for `.. c::automodule: file.h` what would we do? Personally I'd like that to behave like our current directive and document everything, but that is not how `.. py::automodule` works.

**Comment by jnikula** [comment] 2021-06-16 19:19
@jekstrand For 2, I was thinking of a scenario where you have, for example, documented structs foo, bar and baz in a file, but you only add `.. c:autostruct::` for one or two of them. Or, in general, only pull in some of the documentation from a file. I wasn't even referring to the top level comments not bound to any C symbols.

We could dodge the problem in Hawkmoth just by saying it's the user's responsibility, but I think it's a real problem people add documentation comments and forget to include it in `.rst`. (Perhaps part of the appeal in the grouping mechanism is that you could just ensure you have the group specified in the documentation comment, and the whole group gets pulled in.)

What I've seen done in Linux kernel documentation is pulling in specific function and struct documentation first inline in prose, and then pulling in everything separately as "full reference". I don't like this because of the duplication, not only in the documentation, but also in the cross-reference targets.

**Comment by jnikula** [comment] 2021-06-16 19:23
@BrunoMSantos These are the kind of differences that make me wonder about re-using Sphinx autodoc extension. Does it get in the way more than it helps?

**Comment by jekstrand** [comment] 2021-06-16 20:33
> We could dodge the problem in Hawkmoth just by saying it's the user's responsibility, but I think it's a real problem people add documentation comments and forget to include it in .rst. (Perhaps part of the appeal in the grouping mechanism is that you could just ensure you have the group specified in the documentation comment, and the whole group gets pulled in.)

Yeah, I think there's, to a certain extent, a matter of taste here.  I'm starting with a very poorly documented project where things aren't arranged in any sort of pedagogically useful order.  In my opinion, when documenting such a project, giant pages of function signatures, 90% of which are undocumented, is worse than no documentation for those things.  I'd rather if someone wants to look at signatures, they look at the header file.  What's in the docs should be clear and useful.  Again, it's a bit of a matter of taste/opinion, but this is where I'm coming from.

**Comment by BrunoMSantos** [comment] 2021-06-16 23:25
> @BrunoMSantos These are the kind of differences that make me wonder about re-using Sphinx autodoc extension. Does it get in the way more than it helps?

What do you mean by re-using the autodoc extension? I thought autodoc was Python specific and not extensible, I wasn't counting on bolting anything into it. In fact there are other limits to the comparison: (e.g.) autodoc also doesn't have an `autotype` and it has an `autoclass`.

As for the merits of doing it, I prefer in-source composition, but I'm not retrofitting this into an existing code base. Also, Mesa considering Hawkmoth is huge and and we have let the Wayland guys down already for much the same reasons although they were looking for a different solution. Not to mention this is a legitimate request regardless simply because we do deviate substantially from the standard setter: Python's own autodoc.

Implementing Doxygen's `@ingroup` was not the right compromise as we already support better in-source composition, but mimicking Python's autodoc to a greater extent adds something new and seemingly important in the real world.

**Comment by BrunoMSantos** [comment] 2021-06-16 23:28
> [...]  giant pages of function signatures, 90% of which are undocumented [...]

A wild idea appeared. Would those have to be documented with docstrings? If they're not needed in the docs, all you'd need to do would be to use one less `*` on those ;)

**Comment by jekstrand** [comment] 2021-06-17 03:05
I guess I've been assuming doxygen-style "pull in everything" where it shows up docstring or no.  Even if they didn't get automatically pulled in that still doesn't deal with the issue of organization.

**Comment by jnikula** [comment] 2021-06-17 08:50
> What do you mean by re-using the autodoc extension? I thought autodoc was Python specific and not extensible, I wasn't counting on bolting anything into it. In fact there are other limits to the comparison: (e.g.) autodoc also doesn't have an `autotype` and it has an `autoclass`.

It's possible to subclass autodoc documenters, and overload the Python specific parts with C specific parts. The downside is becoming dependent on the guts of the autodoc extension, and I don't trust Sphinx not to change them at will. Also, to understand what is really going on, you have to read a non-trivial amount of Sphinx internals.

I am leaning towards making this independent of the autodoc extension. Mimic what makes sense, and try not to surprise the user with the differences.

**Comment by BrunoMSantos** [comment] 2021-06-17 10:22
Ah sure, we're on the same page then.

**Comment by fooishbar** [comment] 2021-06-18 09:48
>  we have let the Wayland guys down already for much the same reasons although they were looking for a different solution

Hey, we don't feel let down, and we'd still love to come over to Hawkmoth. :) We're just in the same boat as Mesa - our codebase is not arranged well for documentation grouping, and we wanted to get docs out without reorganising everything being in the critical path for it. Now that we do have some docs and some better file-level organisation as well, we can rethink it.

> We could dodge the problem in Hawkmoth just by saying it's the user's responsibility, but I think it's a real problem people add documentation comments and forget to include it in .rst. (Perhaps part of the appeal in the grouping mechanism is that you could just ensure you have the group specified in the documentation comment, and the whole group gets pulled in.)

Yeah, honestly this is my main concern. Having to track the changes both in docstring and in RSt is a worry for me, because as noted, it's easy to notice in review that a docstring doesn't fall into a group, but it's far less easy to look through the RSt and check that everything doc'ed is pulled into the docs.

**Comment by jnikula** [comment] 2021-06-18 10:15
For implementation details, I just noticed Sphinx 3.0 has added meta field lists for the Python Domain. Similar to e.g. `:param foo: ...` you can add `:meta field: value`. The Python Domain only uses `:meta private:`, but the idea could be reused for e.g. `:meta group: my-group`.

This does mean parsing the documentation comments for the meta fields, which I've been opposed to, but there's what I think a crucial difference now: Sphinx provides a function to parse the comment for the meta fields: `sphinx.util.docstrings.separate_metadata`.

I think that information could be used in the autodoc directives, for example:

```
.. c:autofunction:: file.c
   :group: my-group
```

Note the absense of the function name after the file name. This would pull in documentation for all the functions from `file.c` with `:meta group: my-group` in the documentation comment.

**Comment by fooishbar** [comment] 2021-06-18 11:25
Am I right in recalling that parsing is done on-demand by the file list, without caching? So a hypothetical:
```
.. c:autofunction:: file-with-everything.h
    :group: output

.. c:autofunction:: file-with-everything.h
    :group: input
```

would cause `file-with-everything.h` to be parsed twice, and that:
```
.. c:autofunction::
    :group: output

.. c:autofunction::
    :group: input
```

isn't possible because it doesn't know which files to collect from?

**Comment by jnikula** [comment] 2021-06-18 11:50
Implementing caching is pretty much a requirement here. Within a .rst document, it doesn't look too difficult. Across .rst documents, it gets more complicated and I think at first I'd ignore that problem completely. (It's related to Sphinx parallel build.)

Yes, we need some way to indicate the files to collect from. Seems like that too is much easier within a .rst document than making it span multiple .rst documents.

I think it would be possible to add a directive to indicate the file(s) to use in the subsequent `.. c:auto<type>::` directives. It does make the directives stateful, and I am unsure if that's a good thing. I'd probably leave that for a later addition, based on real world needs.

Finally, with this idea of being able to (perhaps in the future) leave out either the filename, or the symbol name, or both, I am slightly wondering about a syntax that would be compatible with that. For a single argument `.. c:autofunction:: foo` I think it should be unambiguous if `foo` refers to a file or a symbol name, without actually looking up filenames or symbols. Moreover, while I am not actively supporting Windows, there are clearly Windows users out there. The syntax needs to be compatible with both Unix and Windows file names.

**Comment by fooishbar** [comment] 2021-06-18 11:52
Yeah, that makes a lot of sense. Being able to specify groups without files is kind of nice I suppose, but far from essential. I'd be very happy with just caching within a `.rst`.

**Comment by BrunoMSantos** [comment] 2021-06-18 12:04
Some good points and ideas!

> Implementing caching is pretty much a requirement here. Within a .rst document, it doesn't look too difficult. Across .rst documents, it gets more complicated and I think at first I'd ignore that problem completely. (It's related to Sphinx parallel build.)

I haven't had time to follow up on it, but I'm looking to solve it with [Sphinx.connect](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.connect) and the `env-before-read-docs` or some other event to plug in a bulk parsing of all files to build a cache. The I need to look into how to keep it in memory and avoid the file system as we pass it around to each and every directive call, but the cache would be built before any of them run.

Again, never tested any of this, but I think it should work fine and accommodate all the fancy stuff we discussed so far. I'm assuming we rebuild the cache from scratch every time by the way.

**Comment by jnikula** [comment] 2021-06-18 12:38
@BrunoMSantos Currently we process the directives and add the documentation comment content at the time Sphinx calls `run()` on the directive, i.e. as it reads the documents. I may be missing something, but IIUC there's only one pass here. We get the directive data (which gives us the files to parse) and we do the work. My understanding is that caching across .rst files means postponing the documentation comment insertion at a later phase in Sphinx build. You'd have to add placeholder nodes, and handle them later. It's not impossible, but deviates quite a bit from how we handle this now.

**Comment by jnikula** [comment] 2021-06-18 12:42
> I'm assuming we rebuild the cache from scratch every time by the way.

Yeah, I think it probably gets too fragile to try to let Sphinx pickle the cache and use it across Sphinx invocations.

**Comment by jnikula** [comment] 2021-06-18 12:54
Something like this is what I'm envisioning ATM for the first steps (and already have some draft code):

1. Split up directive handling from parsing the C files. Read the parsed data to `self.env` on demand, and have the directive pick the data from there.
2. Simplify the type (in this case function, struct, var, etc.) and name metadata from clang objects for easy consumption by the directive.
3. Add the basic auto directives to look up the comments based on filename, type and name from the parsed data.
4. Clean up the cached data to avoid Sphinx auto-pickling.

I think this would be the minimum requirement, and everything else could be built on top this. I don't think any major redesigns are required at this stage.

**Comment by jnikula** [comment] 2021-06-30 21:47
There's a draft to look and maybe give a spin at #53. Still some missing pieces, but should work. Fingers crossed.
While it's not done yet, I'm actually amazed at how lean I managed to keep it: 3 files changed, 155 insertions(+), 47 deletions(-), including documentation. Totally worth it.

**Comment by jnikula** [comment] 2021-09-08 16:34
As a status update, I've posted a bunch of required internal refactoring in #54 and #55. This isn't forgotten. ;)

**Comment by jnikula** [comment] 2021-09-26 12:07
@jekstrand @fooishbar Support for this has now been merged to master. There's an unrelated bug fix I'll want resolved before doing a release with this.

After some back and forth, the syntax turned into:

```
.. c:autostruct:: foo_struct
   :file: filename.c
   :members: foo bar
```

The `:file:` directive option is mandatory (sic) for the time being, but it's an option because we intend to make it actually optional in the future. It's easier and more natural to drop an option than to figure out syntax to make directive arguments optional.

I'm closing this one because the original request has now been implemented. Let's track the additional features in separate issues.

**Closed by jnikula** 2021-09-26 12:07 UTC
Labels: enhancement

**Comment by fooishbar** [comment] 2021-09-30 13:50
Oh, this is awesome! :)
